export { renderMessage } from './Reaccord';

export const Embed = 'Embed';
export const Author = 'Author';
export const Color = 'Color';
export const Desc = 'Desc';
export const Field = 'Field';
export const Footer = 'Footer';
export const Image = 'Image';
export const Timestamp = 'Timestamp';
export const Title = 'Title';
export const Url = 'Url';
export const Row = 'Row';
export const Button = 'Button';
export const LinkButton = 'Button';
export const Select = 'Select';
export const Option = 'Option';
export const Text = 'Text';
export const Br = 'Br';
export const Span = 'Span';
export const Link = 'Link';
export const Code = 'Code';
